#!/usr/bin/ruby
#
# NAME
#   cpuclock
#
# SYNOPSIS:
#   From command line,
#
#     cpuclock
#
#   In batch files,
#
#     art <art_id> do
#       localPathName 'cpuclock'
#     end
#
# DESCRIPTION
#   The 'cpuclock' puts the processor speed in MHz as the ART score to standard output.
#
#   For example, if the processor speed is 1.86GHz, the 'cpuclock' executed from command line
#   prints '1860'.
#
#     cpuclock
#     1860
#
#   In the following case, the job 'job1' in a batch file will be executed on an Xgrid agent
#   whose CPU clock is 1860.
#
#     art 'cpuclock' do
#       localPathName 'cpuclock'
#     end
#
#     job 'job1' do
#       ...
#       ...
#       artConds 'cpuclock'=>{:eq=>1860}
#     end
#
# AUTHOR
#   Tetsuya SUZUKI <tetsuya[at]sic.shibaura-it.ac.jp> (Please replace '[at]' with '@')
#
#

cmd = "/usr/sbin/system_profiler SPHardwareDataType"
stdout = IO.popen(cmd)
stdout.sync = true
while line = stdout.gets
  line.chomp!
  if /Processor Speed:\s*([^\s]*)\s*(.*)/ =~ line
    value = $1
    unit = $2
    break
  end
end
stdout.close

if unit == "MHz"
  puts value
  exit
elsif unit == "GHz"
  puts (value.to_f*1000).to_i
  exit
end
puts 0
