#!/usr/bin/ruby
#
# NAME
#   executable
#
# SYNOPSIS:
#   From command line,
#
#     executable [<filename_1> <filename_2> ... <filename_n>]
#
#   In batch files,
#
#     art <art_id> do
#       localPathName 'executable'
#       arguments <filename_1>, <filename_2>, ..., <filename_n>
#     end
#
# DESCRIPTION
#   The 'executable' checks if all of given file names are executable or not.
#   It puts the ART score 1 to standard output if all of them are executable or 
#   puts the ART score 0 otherwise. If no file name is given, it puts the ART score 1.
#
#   For example, if the file '/usr/bin/bc' is executable, the 'executable' executed
#   from command line with a command line argument '/ust/bin/bc' will print '1'.
#
#     executable /usr/bin/bc
#
#   In the following case, the job 'job1' in a batch file will be executed on an Xgrid agent
#   if the file '/usr/bin/bc' is executable on the agent.
#
#     art 'bcIsExecutable' do
#       localPathName 'executable'
#       arguments '/usr/bin/bc'
#     end
#
#     job 'job1' do
#       ...
#       ...
#       arts 'bcIsExecutable'
#     end
#
# AUTHOR
#   Tetsuya SUZUKI <tetsuya[at]sic.shibaura-it.ac.jp> (Please replace '[at]' with '@')
#
#

ARGV.each {|f|
  if !File.executable?(f)
    puts 0
    exit
  end
}

puts 1
