#!/usr/bin/ruby
#
# NAME
#   hostname
#
# SYNOPSIS:
#   From command line,
#
#     hostname [<regular_expression>]
#
#   In batch files,
#
#     art <art_id> do
#       localPathName 'hostname'
#       arguments <regular_expression>
#     end
#
# DESCRIPTION
#   The 'hostname' checks if a given Ruby's regular expression <regular_expression> matches
#   with the host name on which the 'hostname' runs or not.
#   It puts the ART score 1 to standard output if <regular_expression> matches with the host name
#   or puts the ART score 0 otherwise.
#
#   If you want to know the host name of your machine, run 'hostname' without 
#   any command line argument. It will print the host name.
#
#   For example, it prints '1' if the host name starts with 'macmini' or puts '0' otherwise.
#
#     hostname '^macmini'
#
#   In the following case, the job 'job1' in a batch file will be executed on an Xgrid agent
#   if the host name starts with 'macmini' such as 'macmini00', 'macmini01' and so on.
#
#     art 'onMacmini' do
#       localPathName 'hostname'
#       arguments '^macmini'
#     end
#
#     job 'job1' do
#       ...
#       ...
#       arts 'onMacmini'
#     end
#
# AUTHOR
#   Tetsuya SUZUKI <tetsuya[at]sic.shibaura-it.ac.jp> (Please replace '[at]' with '@')
#
#

expectedValue = ARGV[0]

cmd = "/bin/hostname"
stdout = IO.popen(cmd)
stdout.sync = true
while line = stdout.gets
  line.chomp!
  hostName = line
end
stdout.close

if /#{expectedValue}/ =~ hostName
  puts 1
else
  puts 0
end
