#!/usr/bin/ruby
#
# NAME
#   readable
#
# SYNOPSIS:
#   From command line,
#
#     readable [<filename_1> <filename_2> ... <filename_n>]
#
#   In batch files,
#
#     art <art_id> do
#       localPathName 'readable'
#       arguments <filename_1>, <filename_2>, ..., <filename_n>
#     end
#
# DESCRIPTION
#   The 'readable' checks if all of given file names are readable or not.
#   It puts the ART score 1 to standard output if all of them are readable 
#   or puts the ART score 0 otherwise. If no file name is given, it puts the ART score 1.
#
#   For example, if the file '/usr/bin/bc' is readable, the 'readable' executed
#   from command line will print '1'.
#
#     readable /usr/bin/bc
#
#   In the following case, the job 'job1' in a batch file will be executed on an Xgrid agent
#   if the file '/usr/bin/bc' is readable on the agent.
#
#     art 'bcIsReadable' do
#       localPathName 'readable'
#       arguments '/usr/bin/bc'
#     end
#
#     job 'job1' do
#       ...
#       ...
#       arts 'bcIsReadable'
#     end
#
# AUTHOR
#   Tetsuya SUZUKI <tetsuya[at]sic.shibaura-it.ac.jp> (Please replace '[at]' with '@')
#
#

ARGV.each {|f|
  if !File.readable?(f)
    puts 0
    exit
  end
}

puts 1
